version: 2

workflows:
  single-node:
    steps:
      -
        name: "eva-ci-test"
        command: experiment.run_single_node
        params:
          command: bash run.sh
          container: pytorch/pytorch:latest
          machineType: "GPU+"